project:
  type: book

book:
  title: "openai-cookbook"
  author: "Zh"
  date: "2023/4/18"
  chapters:
    - README.CN.md
    - part: "API USAGE"
      chapters:
        - 

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



